### ISSUE TITLE
pulse server not starting correctly

### ISSUE THREAD

**Issue by mandinka** [bwsw/cs-pulse-server#49]
container starts, however the pulse server itself is not starting

Logs below:

2019-01-18 01:19:25.770:INFO:oejs.session:main: Scavenging every 660000ms,
INFO  2019-01-18 01:19:25,784 [main][slf4j.scala:159] : The cycle class name from the config: com.bwsw.cloudstack.pulse.PulseBootstrap,
ERROR 2019-01-18 01:19:25,911 [main][slf4j.scala:137] : Failed to initialize scalatra application at /pulse,
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'pulse_config',
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152),
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145),
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172),
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184),
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189),
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:264),
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:270),
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37),
	at com.bwsw.cloudstack.pulse.config.PulseConfig.getInfluxConnectionParameters(PulseConfig.scala:48),
	at com.bwsw.cloudstack.pulse.config.PulseConfig.influx(PulseConfig.scala:67),
	at com.bwsw.cloudstack.pulse.PulseBootstrap.<init>(PulseBootstrap.scala:15),
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method),
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62),
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45),
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423),
	at java.lang.Class.newInstance(Class.java:442),
	at org.scalatra.servlet.ScalatraListener.probeForCycleClass(ScalatraListener.scala:55),
	at org.scalatra.servlet.ScalatraListener.configureCycleClass(ScalatraListener.scala:63),
	at org.scalatra.servlet.ScalatraListener.contextInitialized(ScalatraListener.scala:22),
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890),
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532),
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853),
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344),
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501),
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463),
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785),
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261),
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.server.Server.start(Server.java:452),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.server.Server.doStart(Server.java:419),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.runner.Runner.run(Runner.java:518),
	at org.eclipse.jetty.runner.Runner.main(Runner.java:559),
2019-01-18 01:19:25.914:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@22a71081{/pulse,file:///tmp/jetty-0.0.0.0-8080-cs-pulse-server.war-_pulse-any-6271808792993896244.dir/webapp/,UNAVAILABLE}{/cs-pulse-server.war},
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'pulse_config',
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152),
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145),
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172),
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184),
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189),
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:264),
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:270),
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37),
	at com.bwsw.cloudstack.pulse.config.PulseConfig.getInfluxConnectionParameters(PulseConfig.scala:48),
	at com.bwsw.cloudstack.pulse.config.PulseConfig.influx(PulseConfig.scala:67),
	at com.bwsw.cloudstack.pulse.PulseBootstrap.<init>(PulseBootstrap.scala:15),
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method),
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62),
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45),
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423),
	at java.lang.Class.newInstance(Class.java:442),
	at org.scalatra.servlet.ScalatraListener.probeForCycleClass(ScalatraListener.scala:55),
	at org.scalatra.servlet.ScalatraListener.configureCycleClass(ScalatraListener.scala:63),
	at org.scalatra.servlet.ScalatraListener.contextInitialized(ScalatraListener.scala:22),
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890),
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532),
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853),
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344),
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501),
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463),
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785),
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261),
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.server.Server.start(Server.java:452),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.server.Server.doStart(Server.java:419),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.runner.Runner.run(Runner.java:518),
	at org.eclipse.jetty.runner.Runner.main(Runner.java:559),
2019-01-18 01:19:25.931:INFO:oejs.AbstractConnector:main: Started ServerConnector@2d7275fc{HTTP/1.1,[http/1.1]}{0.0.0.0:8080},
2019-01-18 01:19:25.931:INFO:oejs.Server:main: Started @2119ms,

**Comment by bwsw** [comment]
@mandinka It's because the config is missing or incorrect. Please read README.md carefully and pass config properly into the docker app.

**Comment by mandinka** [comment]
Hi,

I fixed the configuration, but still getting a java error (this is running in docker). Thanks in advance!

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45),
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423),
	at java.lang.Class.newInstance(Class.java:442),
	at org.scalatra.servlet.ScalatraListener.probeForCycleClass(ScalatraListener.scala:55),
	at org.scalatra.servlet.ScalatraListener.configureCycleClass(ScalatraListener.scala:63),
	at org.scalatra.servlet.ScalatraListener.contextInitialized(ScalatraListener.scala:22),
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890),
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532),
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853),
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344),
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501),
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463),
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785),
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261),
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.server.Server.start(Server.java:452),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.server.Server.doStart(Server.java:419),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.runner.Runner.run(Runner.java:518),
	at org.eclipse.jetty.runner.Runner.main(Runner.java:559),
2019-02-01 23:53:37.489:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@22a71081{/pulse,file:///tmp/jetty-0.0.0.0-8080-cs-pulse-server.war-_pulse-any-1097962884681978058.dir/webapp/,UNAVAILABLE}{/cs-pulse-server.war},
java.lang.NullPointerException,
	at com.typesafe.config.ConfigException.<init>(ConfigException.java:23),
	at com.typesafe.config.ConfigException$BadPath.<init>(ConfigException.java:198),
	at com.typesafe.config.ConfigException$BadPath.<init>(ConfigException.java:204),
	at com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:170),
	at com.typesafe.config.impl.PathParser.parsePathNodeExpression(PathParser.java:85),
	at com.typesafe.config.impl.PathParser.parsePathNodeExpression(PathParser.java:79),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseKey(ConfigDocumentParser.java:282),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:448),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.consolidateValues(ConfigDocumentParser.java:152),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseArray(ConfigDocumentParser.java:549),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:249),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.consolidateValues(ConfigDocumentParser.java:152),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:471),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:456),
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:646),
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14),
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260),
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248),
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180),
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174),
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299),
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:688),
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:702),
	at com.bwsw.cloudstack.pulse.config.PulseConfig.<init>(PulseConfig.scala:38),
	at com.bwsw.cloudstack.pulse.config.PulseConfig$.apply(PulseConfig.scala:24),
	at com.bwsw.cloudstack.pulse.PulseBootstrap.<init>(PulseBootstrap.scala:15),
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method),
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62),
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45),
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423),
	at java.lang.Class.newInstance(Class.java:442),
	at org.scalatra.servlet.ScalatraListener.probeForCycleClass(ScalatraListener.scala:55),
	at org.scalatra.servlet.ScalatraListener.configureCycleClass(ScalatraListener.scala:63),
	at org.scalatra.servlet.ScalatraListener.contextInitialized(ScalatraListener.scala:22),
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890),
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532),
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853),
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344),
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501),
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463),
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785),
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261),
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.server.Server.start(Server.java:452),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113),
	at org.eclipse.jetty.server.Server.doStart(Server.java:419),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.runner.Runner.run(Runner.java:518),
	at org.eclipse.jetty.runner.Runner.main(Runner.java:559),
2019-02-01 23:53:37.505:INFO:oejs.AbstractConnector:main: Started ServerConnector@65f1d4d6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080},
2019-02-01 23:53:37.506:INFO:oejs.Server:main: Started @2046ms,

**Comment by bwsw** [comment]
@mandinka Hi, just fixed small bug NOT RELATED to your issue, published new Docker image which still runs well, and would like to share our configs with you

```bash
#!/bin/bash
docker rm -f pulse-server
docker pull bwsw/cs-pulse-server
docker run --restart=always -d --name pulse-server \
    -e INFLUX_URL=http://10.252.2.4:8086/ \
    -e INFLUX_USER=pulse \
    -e INFLUX_PASSWORD=secret \
    -e INFLUX_DB=pulse \
    -e NGINX_CACHE_TIME=5s \
    -e NGINX_RATE_LIMIT=20 \
    -v /opt/cs/pulse/server.conf:/etc/pulse/application.conf \
    -p 127.0.0.1:9090:9090 bwsw/cs-pulse-server
```

```
pulse_config {
  influx {
    url =  "http://10.252.2.4:8086"
    url = ${?INFLUX_URL}

    username = "pulse"
    username = ${?INFLUX_USER}

    password = "secret"
    password = ${?INFLUX_PASSWORD}

    database = "pulse"
    database = ${?INFLUX_DB}
  }
  scales = [
    {
      range = "15m"
      aggregation = ["1m", "5m"]
    }
    {
      range = "30m"
      aggregation = ["1m", "5m", "15m"]
    }
    {
      range = "1h"
      aggregation = ["1m", "5m", "15m"]
    }
    {
      range = "2h"
      aggregation = ["5m", "15m", "30m"]
    }
    {
      range = "4h"
      aggregation = ["5m", "15m", "30m", "1h"]
    }
    {
      range = "12h"
      aggregation = ["15m", "30m", "1h"]
    }
    {
      range = "1d"
      aggregation = ["30m", "1h"]
    }
    {
      range = "1w"
      aggregation = ["1h", "4h"]
    }
    {
      range = "30d"
      aggregation = ["4h", "1d"]
    }
    {
      range = "3h"
      aggregation = ["4m", "6m"]
    }
  ]
  shifts = ["m", "h", "d"]
}
```

Works nice, previously published version also works with that config.
